### ISSUE TITLE
Zookeeper_mt library is not found while setting up the software mux.

### ISSUE THREAD

**Issue by jaingeet** [Beamer-LB/beamer-doc#1]
During setting up the software mux, when I am trying to build the FastClick by running the command `make`, it is throwing the following error - 

make[1]: Entering directory '/work/fastclick/userlevel'
  LINK click
/usr/bin/ld: cannot find -lzookeeper_mt
collect2: error: ld returned 1 exit status
Makefile:141: recipe for target 'click' failed
make[1]: *** [click] Error 1
make[1]: Leaving directory '/work/fastclick/userlevel'
Makefile:57: recipe for target 'userlevel' failed
make: *** [userlevel] Error 2

**Comment by vlolteanu** [comment]
You need libzookeeper-mt, which you'll probably find in a package called libzookeeper-mt-dev(el), or something along those lines. I've updated the wiki.

**Comment by jaingeet** [comment]
Thanks. It worked.
